# Generated by Django 2.2.24 on 2021-12-06 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watrustee', '0011_auto_20211130_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticatorpublickey',
            options={'ordering': ['keychain_uid']},
        ),
        migrations.AlterField(
            model_name='authenticatorpublickey',
            name='authenticator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_authenticator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='authenticatorpublickey',
            unique_together={('authenticator_user', 'keychain_uid')},
        ),
        migrations.RemoveField(
            model_name='authenticatorpublickey',
            name='created',
        ),
        migrations.RemoveField(
            model_name='authenticatorpublickey',
            name='modified',
        ),
    ]
