# Generated by Django 2.2.24 on 2022-01-11 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('watrustee', '0012_auto_20211206_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAuthenticator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keystore_uid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='keystore uid')),
                ('keystore_owner', models.CharField(max_length=100, verbose_name='Identity/role of the key guardian')),
                ('keystore_secret', models.CharField(max_length=128, verbose_name='keystore secret uid')),
            ],
            options={
                'verbose_name': 'authenticator user',
                'verbose_name_plural': 'authenticator users',
            },
        ),
        migrations.AlterModelOptions(
            name='authenticatorpublickey',
            options={},
        ),
        migrations.RenameField(
            model_name='authenticatorpublickey',
            old_name='public_key',
            new_name='payload',
        ),
        migrations.AlterField(
            model_name='authenticatorpublickey',
            name='authenticator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_keys', to='watrustee.PublicAuthenticator'),
        ),
        migrations.AlterUniqueTogether(
            name='authenticatorpublickey',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='AuthenticatorUser',
        ),
    ]
