# Generated by Django 2.2.24 on 2022-01-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watrustee', '0013_auto_20220111_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicauthenticator',
            name='keystore_secret',
            field=models.CharField(max_length=128, verbose_name='keystore secret'),
        ),
        migrations.AlterField(
            model_name='publicauthenticator',
            name='keystore_uid',
            field=models.UUIDField(unique=True, verbose_name='keystore uid'),
        ),
    ]
