# Generated by Django 2.2.26 on 2022-01-26 13:41

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('watrustee', '0014_auto_20220111_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicauthenticator',
            name='keystore_owner',
            field=models.CharField(max_length=100, verbose_name='Keystore owner'),
        ),
        migrations.AlterField(
            model_name='publicauthenticator',
            name='keystore_secret',
            field=models.CharField(max_length=128, verbose_name='Keystore secret'),
        ),
        migrations.AlterField(
            model_name='publicauthenticator',
            name='keystore_uid',
            field=models.UUIDField(unique=True, verbose_name='Keystore uid'),
        ),
        migrations.AlterField(
            model_name='trusteekeypair',
            name='private_key',
            field=django_cryptography.fields.encrypt(models.BinaryField(null=True, verbose_name='Private key (PEM format)')),
        ),
    ]
