# Generated by Django 2.2.26 on 2022-01-28 22:34

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAuthenticator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keystore_uid', models.UUIDField(unique=True, verbose_name='Keystore uid')),
                ('keystore_owner', models.CharField(max_length=100, verbose_name='Keystore owner')),
                ('keystore_secret', models.CharField(max_length=128, verbose_name='Keystore secret')),
            ],
            options={
                'verbose_name': 'authenticator user',
                'verbose_name_plural': 'authenticator users',
            },
        ),
        migrations.CreateModel(
            name='AuthenticatorPublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('keychain_uid', models.UUIDField(null=True, verbose_name='Keychain uid')),
                ('key_algo', models.CharField(max_length=20, verbose_name='Key type')),
                ('payload', django_cryptography.fields.encrypt(models.BinaryField(verbose_name='Public key (PEM format)'))),
                ('authenticator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_keys', to='wagateway.PublicAuthenticator')),
            ],
        ),
    ]
