# Generated by Django 2.2.26 on 2022-01-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wagateway", "0002_auto_20220130_2329")]

    operations = [migrations.AlterModelOptions(name="publicauthenticator", options={})]
