# Generated by Django 2.2.26 on 2022-02-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wagateway", "0003_auto_20220130_2335")]

    operations = [migrations.RenameField(model_name="authenticatorpublickey", old_name="payload", new_name="key_value")]
