# Generated by Django 2.2.26 on 2022-02-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagateway', '0004_auto_20220201_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicauthenticator',
            old_name='keystore_secret',
            new_name='keystore_secret_hash',
        ),
    ]
