# Generated by Django 3.1 on 2022-06-14 08:50

from django.db import migrations, models
import django_cryptography.fields
import wacryptolib.utilities


class Migration(migrations.Migration):

    dependencies = [("wagateway", "0007_auto_20220613_1725")]

    operations = [
        migrations.RenameField(
            model_name="symkeydecryptionrequest", old_name="decryption_status", new_name="symkey_decryption_status"
        ),
        migrations.RemoveField(model_name="revelationrequest", name="response_key_algo"),
        migrations.RemoveField(model_name="revelationrequest", name="response_keychain_uid"),
        migrations.RemoveField(model_name="revelationrequest", name="response_public_key"),
        migrations.AddField(
            model_name="revelationrequest",
            name="revelation_response_key_algo",
            field=models.CharField(default="", max_length=20, verbose_name="Revelation response Key algo"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="revelationrequest",
            name="revelation_response_keychain_uid",
            field=models.UUIDField(null=True, verbose_name="Revelation response keychain uid"),
        ),
        migrations.AddField(
            model_name="revelationrequest",
            name="revelation_response_public_key",
            field=django_cryptography.fields.encrypt(
                models.BinaryField(default="", verbose_name="Revelation response Public key ")
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="symkeydecryptionrequest",
            name="symkey_decryption_request_data",
            field=django_cryptography.fields.encrypt(
                models.BinaryField(
                    default="", verbose_name="Symkey Request data (symkey/shard encrypted by target authenticator)"
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="symkeydecryptionrequest",
            name="symkey_decryption_response_data",
            field=django_cryptography.fields.encrypt(
                models.BinaryField(
                    default=b"", verbose_name="Symkey Response data (symkey/shard encrypted by response public key)"
                )
            ),
        ),
        migrations.AlterField(
            model_name="revelationrequest",
            name="revelation_request_description",
            field=models.TextField(blank=True, verbose_name="Revelation request description"),
        ),
        migrations.AlterField(
            model_name="revelationrequest",
            name="revelation_request_uid",
            field=models.UUIDField(
                default=wacryptolib.utilities.generate_uuid0, unique=True, verbose_name="Revelation request uid"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="symkeydecryptionrequest", unique_together={("revelation_request", "symkey_decryption_request_data")}
        ),
        migrations.RemoveField(model_name="symkeydecryptionrequest", name="request_data"),
        migrations.RemoveField(model_name="symkeydecryptionrequest", name="response_data"),
    ]
