# Generated by Django 3.2.13 on 2022-07-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wagateway", "0008_auto_20220614_1050")]

    operations = [
        migrations.RenameField(
            model_name="symkeydecryptionrequest",
            old_name="public_authenticator_key",
            new_name="target_public_authenticator_key",
        )
    ]
