# Generated by Django 3.2.13 on 2022-07-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagateway', '0009_rename_public_authenticator_key_symkeydecryptionrequest_target_public_authenticator_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicauthenticatorkey',
            old_name='authenticator_user',
            new_name='public_authenticator',
        ),
    ]
