# Generated by Django 3.2.13 on 2022-07-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wagateway", "0010_rename_authenticator_user_publicauthenticatorkey_public_authenticator")]

    operations = [
        migrations.AlterField(
            model_name="symkeydecryptionrequest",
            name="symkey_decryption_status",
            field=models.CharField(
                choices=[
                    ("DECRYPTED", "DECRYPTED"),
                    ("PRIVATE_KEY_MISSING", "PRIVATE KEY MISSING"),
                    ("CORRUPTED", "CORRUPTED"),
                    ("METADATA_MISMATCH", "METADATA_MISMATCH"),
                    ("PENDING", "PENDING"),
                ],
                default="PENDING",
                max_length=128,
            ),
        )
    ]
