# Generated by Django 3.2.13 on 2022-07-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagateway', '0011_alter_symkeydecryptionrequest_symkey_decryption_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symkeydecryptionrequest',
            name='cryptainer_metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Cryptainer metadata)'),
        ),
        migrations.AlterUniqueTogether(
            name='symkeydecryptionrequest',
            unique_together={('revelation_request', 'symkey_decryption_request_data', 'target_public_authenticator_key')},
        ),
    ]
