# Generated by Django 3.1 on 2022-07-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagateway', '0012_auto_20220714_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicauthenticator',
            name='keystore_creation_datetime',
            field=models.DateTimeField(null=True, verbose_name='Keystore creation datetime'),
        ),
        migrations.AddField(
            model_name='publicauthenticator',
            name='last_retrieval_datetime',
            field=models.DateTimeField(null=True, verbose_name='Last retrieval date'),
        ),
        migrations.AddField(
            model_name='publicauthenticator',
            name='retrieval_count',
            field=models.IntegerField(default=0, verbose_name='Retrieval count'),
        ),
    ]
