# Generated by Django 2.2.5 on 2019-09-17 19:42

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowKeypair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keychain_uid', models.UUIDField(verbose_name='Keychain uid')),
                ('key_type', models.CharField(max_length=20, verbose_name='Key type')),
                ('key_pair', django_cryptography.fields.encrypt(models.TextField(verbose_name='Key pair'))),
            ],
            options={
                'verbose_name': 'escrow key pair',
                'verbose_name_plural': 'escrow key pairs',
                'unique_together': {('keychain_uid', 'key_type')},
            },
        ),
    ]
