# Generated by Django 2.2.24 on 2021-11-23 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('waescrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatorPublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('keychain_uid', models.UUIDField(null=True, verbose_name='Keychain uid')),
                ('key_algo', models.CharField(max_length=20, verbose_name='Key type')),
                ('public_key', django_cryptography.fields.encrypt(models.BinaryField(verbose_name='Public key (PEM format)'))),
                ('authenticator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='authenticator user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
