# Generated by Django 2.2.5 on 2019-09-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waescrow', '0003_escrowkeypair_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowkeypair',
            name='decrytion_authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
