# Generated by Django 2.2.24 on 2021-11-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waescrow', '0003_auto_20211123_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatoruser',
            name='username',
            field=models.CharField(max_length=128, unique=True, verbose_name='keychain uid'),
        ),
    ]
