# Generated by Django 2.2.5 on 2019-09-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waescrow', '0004_escrowkeypair_decrytion_authorized_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escrowkeypair',
            old_name='decrytion_authorized_at',
            new_name='decryption_authorized_at',
        ),
    ]
