# Generated by Django 2.2.24 on 2021-11-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waescrow', '0005_auto_20211124_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatoruser',
            name='username',
            field=models.UUIDField(null=True, unique=True, verbose_name='keychain uid'),
        ),
    ]
