# Generated by Django 2.2.24 on 2021-11-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waescrow', '0006_auto_20211129_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatoruser',
            name='username',
            field=models.CharField(default=3, max_length=128, unique=True, verbose_name='keychain uid'),
            preserve_default=False,
        ),
    ]
