# Generated by Django 2.2.6 on 2019-11-10 22:41

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('waescrow', '0006_auto_20191110_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowkeypair',
            name='private_key',
            field=django_cryptography.fields.encrypt(models.BinaryField(verbose_name='Private key (PEM format)')),
        ),
        migrations.AlterField(
            model_name='escrowkeypair',
            name='public_key',
            field=django_cryptography.fields.encrypt(models.BinaryField(verbose_name='Public key (PEM format)')),
        ),
    ]
