# Generated by Django 2.2.6 on 2019-12-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waescrow', '0007_auto_20191110_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowkeypair',
            name='keychain_uid',
            field=models.UUIDField(null=True, verbose_name='Keychain uid'),
        ),
    ]
