# Generated by Django 2.2.24 on 2021-11-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waescrow', '0007_auto_20211129_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatoruser',
            name='username',
            field=models.UUIDField(null=True, unique=True, verbose_name='keychain uid'),
        ),
    ]
