# Generated by Django 2.2.8 on 2019-12-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waescrow', '0008_auto_20191203_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowkeypair',
            name='attached_at',
            field=models.DateTimeField(null=True, verbose_name='Attachment of free key to keychain uid'),
        ),
        migrations.AlterField(
            model_name='escrowkeypair',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation of record'),
        ),
    ]
