# Generated by Django 2.2.26 on 2022-02-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watrustee', '0003_auto_20220130_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trusteekeypair',
            options={},
        ),
        migrations.AlterField(
            model_name='trusteekeypair',
            name='keychain_uid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Keychain uid'),
        ),
    ]
